### ISSUE TITLE
Failed to load external subtitles

### ISSUE THREAD

**Issue by bilalmalkoc** [aflextr/turkcealtyaziorg-stremio-addon#1]
Selamlar. Altyazi secince baslikta belirttigim hatayi veriyor.

<img width="425" alt="Screenshot 2024-05-22 at 09 30 01" src="https://github.com/aflextr/turkcealtyaziorg-stremio-addon/assets/23140025/98c2b519-dd45-4c75-b0d6-6fe09d6122ff">

**Comment by aflextr** [comment]
> Selamlar. Altyazi secince baslikta belirttigim hatayi veriyor.
> 
> <img alt="Screenshot 2024-05-22 at 09 30 01" width="425" src="https://private-user-images.githubusercontent.com/23140025/332684235-98c2b519-dd45-4c75-b0d6-6fe09d6122ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODg2MzcsIm5iZiI6MTcxNjM4ODMzNywicGF0aCI6Ii8yMzE0MDAyNS8zMzI2ODQyMzUtOThjMmI1MTktZGQ0NS00Yzc1LWIwZDYtNmZlMDlkNjEyMmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE0MzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YzA1M2ZhMzdlMDcwN2M3OWMyNzNhODRhMmRiYmYyZDQ4MWJkMGRmNjBlMTljOGJjMTU2ZmEzZTBhYWE4ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pTFB4UxVZiNzxqisEFwT1OFi00iJQSCoq-VOj5sUHNc">

Hangi dizi veya filmin bölümünden bu aldığınız hatayı aldınız acaba ?

**Comment by bilalmalkoc** [comment]
Hepsinde var. Test ettiklerimi atayım:

https://web.stremio.com/#/detail/series/tt2788316/tt2788316%3A1%3A1
https://web.stremio.com/#/detail/movie/tt0137523/tt0137523
https://web.stremio.com/#/detail/movie/tt14539740/tt14539740

**Comment by aflextr** [comment]
> Hepsinde var. Test ettiklerimi atayım:
> 
> https://web.stremio.com/#/detail/series/tt2788316/tt2788316%3A1%3A1 https://web.stremio.com/#/detail/movie/tt0137523/tt0137523 https://web.stremio.com/#/detail/movie/tt14539740/tt14539740

şuan test ettim bende çalışıyor. eğer web sürümü kullanıyorsanız arkada stremionun hizmeti ya da uygulaması açık olması lazım, açık olarak test edebilir misiniz ?

**Comment by bilalmalkoc** [comment]
Evet sorun buymuş. Stremio service silmiştim çünkü video yüklenmesini yavaşlatıyordu.

**Comment by bilalmalkoc** [comment]
@aflextr hocam 9-1-1 dizisine bakar misin onda Turkce secenegi gelmiyor hic.

**Comment by aflextr** [comment]
> @aflextr hocam 9-1-1 dizisine bakar misin onda Turkce secenegi gelmiyor hic.

![image](https://github.com/aflextr/turkcealtyaziorg-stremio-addon/assets/53778891/c616f305-4a34-4465-a9f2-0c7ba3507d77)

bende geliyor. sizde hangi bölümde gelmiyor

**Comment by bilalmalkoc** [comment]
7. sezona bakiyorum

https://share.cleanshot.com/tSQnhWlF

**Comment by aflextr** [comment]
> 7. sezona bakiyorum
> 
> https://share.cleanshot.com/tSQnhWlF

7.sezonu turkcealtyazi.org da yok.
