### ISSUE TITLE
Eklenti çalışmıyor

### ISSUE THREAD

**Issue by oyedikat** [aflextr/turkcealtyaziorg-stremio-addon#4]
Son stremio güncellemesi sonrası eklenti çalışmıyor   1.6.11 sürümünü kullanıyorum

**Comment by aflextr** [comment]
Şuan bir filmde test ettiğimde eklenti çalışıyor . stremio'yu son sürüme güncelleyin ve web sürümü kullanıyorsanız arkada stremio'nun açık olması lazım. eğer hayla da çalışmıyorsa, dizi ya da filmin ismi ve bölümünü söylerseniz bir bakabilirim.

**Comment by oyedikat** [comment]
Şimdi biraz daha kurcaladım örneğin mad maxin bazı torrent linklerinde çalışıyor bazılarında çalışmıyor. Rick and morty izliyordum onda hiç çalışmıyor gibi

**Comment by aflextr** [comment]
> Şimdi biraz daha kurcaladım örneğin mad maxin bazı torrent linklerinde çalışıyor bazılarında çalışmıyor. Rick and morty izliyordum onda hiç çalışmıyor gibi

![image](https://github.com/aflextr/turkcealtyaziorg-stremio-addon/assets/53778891/1b3a1840-6c1b-4b47-b656-5980f334b096)

rick and morty türkçealtyaziorg sitesinde 7.sezon 5.bölüme kadar var ileriki bölümlerde çıkmaması normal.

**Comment by oyedikat** [comment]
> > Şimdi biraz daha kurcaladım örneğin mad maxin bazı torrent linklerinde çalışıyor bazılarında çalışmıyor. Rick and morty izliyordum onda hiç çalışmıyor gibi
> 
> ![image](https://private-user-images.githubusercontent.com/53778891/346291043-1b3a1840-6c1b-4b47-b656-5980f334b096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTE3MzksIm5iZiI6MTcyMDM1MTQzOSwicGF0aCI6Ii81Mzc3ODg5MS8zNDYyOTEwNDMtMWIzYTE4NDAtNmMxYi00YjQ3LWI2NTYtNTk4MGYzMzRiMDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDExMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNWZmNDc2OTA0NzRhMTlhYTlhYmY5Y2M4YTc0OGM1MDIyMzA1NzM4YmMxZGMyYTNmNWY1MGMwMmQyNGUwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lbX9zIdA3tqRVLQObZRKvBaejtUAHaHEKVQN4xnR_9M)
> 
> rick and morty türkçealtyaziorg sitesinde 7.sezon 5.bölüme kadar var ileriki bölümlerde çıkmaması normal.

Sanırım sorun android tv sürümünde masaüstü uygulamasından baktığımda bir sorun yok ancak tv uygulamasında problem var. Bazı linklerde çalışıyor ama çoğunda altyazı gelmiyor

**Comment by aflextr** [comment]
> > > Şimdi biraz daha kurcaladım örneğin mad maxin bazı torrent linklerinde çalışıyor bazılarında çalışmıyor. Rick and morty izliyordum onda hiç çalışmıyor gibi
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/53778891/346291043-1b3a1840-6c1b-4b47-b656-5980f334b096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTE3MzksIm5iZiI6MTcyMDM1MTQzOSwicGF0aCI6Ii81Mzc3ODg5MS8zNDYyOTEwNDMtMWIzYTE4NDAtNmMxYi00YjQ3LWI2NTYtNTk4MGYzMzRiMDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDExMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNWZmNDc2OTA0NzRhMTlhYTlhYmY5Y2M4YTc0OGM1MDIyMzA1NzM4YmMxZGMyYTNmNWY1MGMwMmQyNGUwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lbX9zIdA3tqRVLQObZRKvBaejtUAHaHEKVQN4xnR_9M)
> > rick and morty türkçealtyaziorg sitesinde 7.sezon 5.bölüme kadar var ileriki bölümlerde çıkmaması normal.
> 
> Sanırım sorun android tv sürümünde masaüstü uygulamasından baktığımda bir sorun yok ancak tv uygulamasında problem var. Bazı linklerde çalışıyor ama çoğunda altyazı gelmiyor

Android tvlerde son updateden sonra altyazı problemi var maalesef
