### ISSUE TITLE
Masaüstü sürümde hata veriyor

### ISSUE THREAD

**Issue by zaza123433** [aflextr/turkcealtyaziorg-stremio-addon#5]
Web sürümünde sıkıntısız çalışmasına rağmen masaüstünde hata verip duruyor ama önceden sorun yoktu, son 1 aydır falan böyle.
![w](https://github.com/user-attachments/assets/1bcff129-d05b-4928-b557-5eceacd0df60)

**Comment by aflextr** [comment]
> Web sürümünde sıkıntısız çalışmasına rağmen masaüstünde hata verip duruyor ama önceden sorun yoktu, son 1 aydır falan böyle. ![w](https://private-user-images.githubusercontent.com/155374624/349267125-1bcff129-d05b-4928-b557-5eceacd0df60.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDUwODgsIm5iZiI6MTcyMTMwNDc4OCwicGF0aCI6Ii8xNTUzNzQ2MjQvMzQ5MjY3MTI1LTFiY2ZmMTI5LWQwNWItNDkyOC1iNTU3LTVlY2VhY2QwZGY2MC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMjEzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDdjZDE2Y2MyZmM5YmY1MjE0MzMxZDYxNjE4MjU3MWIxOGVlMDg5OThlMDFkY2JhMGVhOGQ5ZTZhMDYzYzhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ug4QJQtnCO8aUjOL9G6AOsgnBWb7INKvkAg5ATa6eLc)

Güncelleme yayınladım. Sorun hayla devam ediyor mu ?.

**Comment by zaza123433** [comment]
Düzeldi sağolun.
